### ISSUE TITLE
Программу никто не поймет

### ISSUE THREAD

**Issue by mabramovsd** [NeverMine17/astar-sfml#1]
У тебя задание:
Нужно написать программу, которая будет выводить на экран карту уровня игры в зависимости от выбора пользователя. На первом этапе пользователь отвечает на единственный вопрос:
-Выберите игру. 1 — танки, 2 — PacMan, 3 — лабиринт какой-нибудь.
Пользователь вводит число, а в ответ программа выводит на экран карту уровня игры (рисунок или картинку из интернета). Поверх карты программно (не в Paint, а в C++) подрисовывается точка старта (в любую точку, любое оформление — флажок, черная дыра).

Лучше сделать это простыми средствами. Представь ситуацию: есть компания, которая пишет сайт на PHP. Ты приходишь и говоришь: Ruby круче, я буду писать на Ruby. Ок, пиши на Ruby, но т.к. его никто не знает, ты пишешь сайт в одиночку. Срок тот же, требования те же, зарплата та же. Поэтому не надо здесь слов virtual, enum, class, define, protected. Иначе у тебя будет проблема: НА КАЖДОМ ЗАНЯТИИ ты 40 минут будешь объяснять следующему за тобой программисту смысл этих слов. 

P.S. Если хочешь писать путевую карту уровня игры, делай это тут - https://github.com/IngenerkaTeamNewYork/LevelMap . Ну или создай новый репозиторий по своему усмотрению. И, повторюсь, старайся писать код, понятный всем, с кем ты учишься (слова enum, class у нас будут, все остальные - вряд ли). Иначе будешь писать свой код в одиночку, и заведомо не получишь стипендию (Алена+Данила+Юра гарантированно создадут штуку, более красивую по юзабилити)

**Comment by nm17** [comment]
Это старый код. В новой версии я уже убрал все ненужное. Скоро выложу.

**Comment by nm17** [comment]
@mabramovsd Можете посмотреть коммит 69c68b4.
В нем я добавил новый алгоритм поиска короткого пути. Сам код я не делал с нуля а взял с другого проекта и доработал. А именно:

  - Теперь решение выводиться на экран. До этого сохранялось в картинку.
  - Также добавил несколько проверок на ошибки. Теперь нельзя выходить за пределы максимального 32-битного числа.
  - И всякие косметические штуки.
